[workspace]
members = ["src/*"]
resolver = "2"

[profile.dev.package.scrypt]
opt-level = 3

[profile.test.package.scrypt]
opt-level = 3

[profile.release]
strip = true

[profile.release-ffi]
inherits = "release"
lto = true
