[package]
name = "wren"
version = "0.1.0"
edition = "2018"

[dependencies]
getopts = "0.2.21"
anyhow = "1.0.43"
getrandom = "0.2.3"
x25519-dalek = "1.1.1"
chacha20poly1305 = "0.8.1"
scrypt = "0.7.0"
hex = "0.4.3"
regex = "1.5.4"
base64 = "0.13.0"

[profile.dev.package.scrypt]
opt-level = 3

[profile.test.package.scrypt]
opt-level = 3