[package]
name = "wren"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
anyhow = "1.0.43"
rand = "0.8.4"
x25519-dalek = "1.1.1"