[package]
name = "wren"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
wren-crypto = { path = "./crypto", version = "0.1.0" }
base64 = "0.13.0"
getopts = "0.2.21"
anyhow = "1.0.44"
rpassword = "5.0.1"

[dev-dependencies]
hex = "0.4.3"

[workspace]
members = ["crypto"]

[profile.dev.package.scrypt]
opt-level = 3

[profile.test.package.scrypt]
opt-level = 3
