[package]
name = "kestrel-cli"
version = "0.10.1"
edition = "2021"
rust-version = "1.59"
authors = [
    "Kyle Schreiber <kyle@80x24.net>",
]
readme = "README.md"
license = "BSD-3-Clause"
description = "Kestrel file encryption program"
repository = "https://github.com/finfet/kestrel"
homepage = "https://getkestrel.com"
keywords = ["encryption", "file"]
categories = ["command-line-utilities", "cryptography"]

[[bin]]
name = "kestrel"
path = "src/main.rs"

[dependencies]
kestrel-crypto = { path = "../crypto", version = "0.10.1" }
base64 = "0.21.0"
getopts = "0.2.21"
anyhow = "1.0"
passterm = "1.1.7"
zeroize = "1"

[dev-dependencies]
hex = "0.4.3"
