[package]
name = "kestrel-crypto"
version = "3.0.0"
edition = "2021"
authors = [
    "Kyle Schreiber <kyle@80x24.net>",
]
readme = "README.md"
license = "BSD-3-Clause"
description = "Cryptography backend for Kestrel"
repository = "https://github.com/finfet/kestrel"
homepage = "https://github.com/finfet/kestrel"
documentation = "https://docs.rs/kestrel-crypto/"
categories = ["cryptography"]

[dependencies]
getrandom = "0.2.15"
x25519-dalek = { version = "2", default-features = false }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10.8", default-features = false }
hmac = { version = "0.12.1", default-features = false }
hkdf = { version = "0.12.4", default-features = false }
scrypt = { version = "0.11.0", default-features = false }
zeroize = "1.8"

[dev-dependencies]
hex = "0.4.3"

[features]
default = [ "std" ]
std = []
