[package]
name = "wren-crypto"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.3"
x25519-dalek = "1.2.0"
chacha20poly1305 = "0.9.0"
sha2 = "0.9.8"
hmac = "0.11.0"
scrypt = { version = "0.8.0", default-features = false }

[dev-dependencies]
hex = "0.4.3"
