name: Build Release
on:
  push:
    branches:
      - main
    tags:
      - v0.*
      - v1.*

jobs:
  release-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Build Dependencies
        run: |
          rustup target add x86_64-unknown-linux-musl
          rustup target add aarch64-unknown-linux-musl
          sudo apt-get install -y gcc-aarch64-linux-gnu rpm
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Release
        run: make all-linux
      - name: Upload Release Archive
        uses: actions/upload-artifact@v3
        with:
          name: release-linux
          path: build/release-linux-*.tar.gz
  release-macos:
    runs-on: macos-latest
    steps:
      - name: Install Build Dependencies
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Release
        run: make all-macos
      - name: Upload Release Archive
        uses: actions/upload-artifact@v3
        with:
          name: release-macos
          path: build/release-macos-*.tar.gz
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Install Build Dependencies
        run: |
          rustup target add x86_64-pc-windows-msvc
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Release
        run: |
          .\windows-installer.ps1 all
        shell: powershell
      - name: Upload Release Archive
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: build/release-windows-*.zip
